GET_FEEDBACKS = 'GET_FEEDBACKS';
GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
GET_FEEDBACKS_FAILURE = 'GET_FEEDBACKS_FAILURE';

ADD_FEEDBACK = 'ADD_FEEDBACK';
ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
ADD_FEEDBACK_FAILURE = 'ADD_FEEDBACK_FAILURE';

DELETE_FEEDBACK = 'DELETE_FEEDBACK';
DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
DELETE_FEEDBACK_FAILURE = 'DELETE_FEEDBACK_FAILURE';

UPDATE_FEEDBACK = 'UPDATE_FEEDBACK';
UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS';
UPDATE_FEEDBACK_FAILURE = 'UPDATE_FEEDBACK_FAILURE';

LOGIN = 'LOGIN';
LOGOUT = 'LOGOUT';

FETCH_USERS = 'FETCH_USERS';
ADD_USER = 'ADD_USER';
